package de.lindow_it.backend;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import de.lindow_it.backend.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        //Empty
    }
}
